const fs = require('fs');
const path = require('path');
const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');

// Launcher shortcuts: touch and hold the app icon. Android's nearest thing to
// the Siri phrases in plugins/withSiriShortcuts.js, and they take the same
// route — the app's own URL scheme — so a task started here is written exactly
// the way a typed one is.
//
// Labels and icons live with the widgets in modules/planner-widgets-android;
// only the XML is generated, because each intent has to name the app's
// package. Kept in step with ANDROID_SHORTCUTS in
// components/WidgetsSiriSection.tsx.

const SHORTCUTS = [
  { id: 'add_task', icon: 'task', url: 'nwplanner://tasks?new=' },
  { id: 'add_reminder', icon: 'reminder', url: 'nwplanner://reminders?new=' },
  { id: 'ask_copilot', icon: 'copilot', url: 'nwplanner://copilot' },
  { id: 'calendar', icon: 'calendar', url: 'nwplanner://calendar' },
];

const RESOURCE = 'planner_shortcuts';

function shortcutsXml(packageName) {
  const items = SHORTCUTS.map(({ id, icon, url }) => `  <shortcut
    android:shortcutId="${id}"
    android:enabled="true"
    android:icon="@drawable/planner_shortcut_${icon}"
    android:shortcutShortLabel="@string/planner_shortcut_${icon}_short"
    android:shortcutLongLabel="@string/planner_shortcut_${icon}_long">
    <intent
      android:action="android.intent.action.VIEW"
      android:targetPackage="${packageName}"
      android:data="${url.replace(/&/g, '&amp;')}" />
  </shortcut>`).join('\n');
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidAppShortcuts.js; edits here are discarded by prebuild. -->
<shortcuts xmlns:android="http://schemas.android.com/apk/res/android">
${items}
</shortcuts>
`;
}

module.exports = config => {
  config = withDangerousMod(config, ['android', async result => {
    const packageName = result.android?.package;
    if (!packageName) throw new Error('withAndroidAppShortcuts needs android.package');
    const directory = path.join(result.modRequest.platformProjectRoot, 'app/src/main/res/xml');
    fs.mkdirSync(directory, { recursive: true });
    fs.writeFileSync(path.join(directory, `${RESOURCE}.xml`), shortcutsXml(packageName));
    return result;
  }]);

  return withAndroidManifest(config, result => {
    const activity = AndroidConfig.Manifest.getMainActivityOrThrow(result.modResults);
    activity['meta-data'] = (activity['meta-data'] ?? [])
      .filter(item => item.$['android:name'] !== 'android.app.shortcuts');
    activity['meta-data'].push({
      $: { 'android:name': 'android.app.shortcuts', 'android:resource': `@xml/${RESOURCE}` },
    });
    return result;
  });
};
