const { IOSConfig } = require('@expo/config-plugins');

const { withBuildSourceFile } = IOSConfig.XcodeProjectFile;

// Siri and the Shortcuts app, via App Intents.
//
// There is no Expo package for App Intents, so this is Swift the project owns.
// It is injected rather than committed under ios/, because ios/ is generated
// and gitignored — the same reason plugins/withUISceneLifecycle.js exists.
//
// Two shapes of intent live here, and the split is the whole design:
//
//   Writing intents open the app. They carry the dictated values through the
//   app's own URL scheme and let the existing JavaScript do the work, so a task
//   added by voice travels exactly the path a typed one does — encrypted at
//   rest, written through the audit log, queued in the outbox when offline.
//   Creating records natively would mean a second implementation of all of
//   that, in a language with no tests in this repo.
//
//   The reading intent does not open the app. It answers from the App Group
//   container the home screen widgets already read, which costs nothing
//   privacy-wise because those exact numbers are already on the Lock Screen —
//   and it speaks counts and times only, never a record's title, because Siri
//   may be answering on a HomePod or in CarPlay.
//
// What is deliberately absent: AppEntity and EntityQuery, which would let a
// student say "mark Essay draft as done". The system resolves entity
// parameters before perform() runs, with the app possibly not launched and the
// device possibly locked — so answering would mean either reimplementing
// XChaCha20-Poly1305 and the AsyncStorage layout in Swift, or publishing every
// task title into the App Group in plaintext. Both are worse than not having
// the feature.
//
// Credential note: every file here compiles into the existing app target. No
// extension, no new bundle id, no entitlement — App Intents need none, and the
// App Group is already there for the widgets. Nothing in this plugin triggers
// a provisioning change.
//
// Filenames stay flat. withBuildSourceFile derives the Xcode group from the
// file's dirname, and a nested path asserts on a group prebuild never created.

const SHARED_STORE = `// Generated by plugins/withSiriShortcuts.js — edits here are discarded by prebuild.
import Foundation

/// Reads the numbers the app already publishes for the home screen widgets.
///
/// This is the only planner data legible outside the encrypted store, and that
/// is deliberate: counts and clock times, nothing else. Nothing here decrypts
/// anything, because it cannot — the key is in the app's Keychain, marked
/// unlocked-this-device-only, and the ciphertext layout lives in JavaScript.
enum PlannerSharedStore {
  static let suiteName = "group.com.nwmissouri.studentplanner"
  private static let timelineKey = "__expo_widgets_DueToday_timeline"

  struct Snapshot {
    let dueToday: Int
    let overdue: Int
    let doneToday: Int
    let totalToday: Int
    let nextAt: Date?
    let empty: Bool
  }

  static func snapshot(at now: Date = Date()) -> Snapshot? {
    guard let defaults = UserDefaults(suiteName: suiteName),
          let raw = defaults.array(forKey: timelineKey) else { return nil }

    let entries: [(date: Date, props: [String: Any])] = raw.compactMap { element in
      guard let entry = element as? [String: Any],
            let timestamp = entry["timestamp"] as? NSNumber,
            let props = entry["props"] as? [String: Any] else { return nil }
      return (Date(timeIntervalSince1970: timestamp.doubleValue / 1000), props)
    }
    guard !entries.isEmpty else { return nil }

    // The entry in force right now, chosen the same way WidgetKit would: the
    // latest one that has already started, or the earliest if none has.
    let current = entries.filter { $0.date <= now }.max { $0.date < $1.date }
      ?? entries.min { $0.date < $1.date }
    guard let props = current?.props else { return nil }

    let nextAtMs = (props["nextAt"] as? NSNumber)?.doubleValue ?? 0

    return Snapshot(
      dueToday: (props["dueToday"] as? NSNumber)?.intValue ?? 0,
      overdue: (props["overdue"] as? NSNumber)?.intValue ?? 0,
      doneToday: (props["doneToday"] as? NSNumber)?.intValue ?? 0,
      totalToday: (props["totalToday"] as? NSNumber)?.intValue ?? 0,
      nextAt: nextAtMs > 0 ? Date(timeIntervalSince1970: nextAtMs / 1000) : nil,
      empty: (props["empty"] as? NSNumber)?.boolValue ?? true
    )
  }
}
`;

const ENUMS = `// Generated by plugins/withSiriShortcuts.js — edits here are discarded by prebuild.
import AppIntents

/// Task priority, as Siri and the Shortcuts editor offer it.
///
/// The raw values match Task['priority'] in types/index.ts exactly, so the trip
/// out through the URL scheme and back into JavaScript is lossless.
@available(iOS 16.0, *)
enum PlannerPriority: String, AppEnum {
  case high
  case medium
  case low

  static var typeDisplayRepresentation: TypeDisplayRepresentation {
    TypeDisplayRepresentation(name: "Priority")
  }

  static var caseDisplayRepresentations: [PlannerPriority: DisplayRepresentation] = [
    .high: DisplayRepresentation(title: "High", subtitle: "Do this first"),
    .medium: DisplayRepresentation(title: "Medium", subtitle: "Normal work"),
    .low: DisplayRepresentation(title: "Low", subtitle: "Whenever there's time"),
  ]
}

/// The built-in categories, matching BUILT_IN in api/categories.ts.
///
/// A static list rather than the student's own categories: a live list needs a
/// query that runs before the app is open, which cannot read the encrypted
/// store. Custom categories are still available inside the app.
@available(iOS 16.0, *)
enum PlannerCategory: String, AppEnum {
  case homework
  case exam
  case project
  case reading
  case lab
  case other

  static var typeDisplayRepresentation: TypeDisplayRepresentation {
    TypeDisplayRepresentation(name: "Category")
  }

  static var caseDisplayRepresentations: [PlannerCategory: DisplayRepresentation] = [
    .homework: DisplayRepresentation(title: "Homework"),
    .exam: DisplayRepresentation(title: "Exam"),
    .project: DisplayRepresentation(title: "Project"),
    .reading: DisplayRepresentation(title: "Reading"),
    .lab: DisplayRepresentation(title: "Lab"),
    .other: DisplayRepresentation(title: "Other"),
  ]

  /// The spelling the app stores, which is capitalised.
  var storedName: String {
    switch self {
    case .homework: return "Homework"
    case .exam: return "Exam"
    case .project: return "Project"
    case .reading: return "Reading"
    case .lab: return "Lab"
    case .other: return "Other"
    }
  }
}

/// Where "open my planner" should land.
@available(iOS 16.0, *)
enum PlannerScreen: String, AppEnum {
  case dashboard
  case tasks
  case reminders
  case calendar
  case notes
  case copilot

  static var typeDisplayRepresentation: TypeDisplayRepresentation {
    TypeDisplayRepresentation(name: "Screen")
  }

  static var caseDisplayRepresentations: [PlannerScreen: DisplayRepresentation] = [
    .dashboard: DisplayRepresentation(title: "My day"),
    .tasks: DisplayRepresentation(title: "Tasks"),
    .reminders: DisplayRepresentation(title: "Reminders"),
    .calendar: DisplayRepresentation(title: "Calendar"),
    .notes: DisplayRepresentation(title: "Notes"),
    .copilot: DisplayRepresentation(title: "Copilot"),
  ]

  /// The dashboard is the app's root route, so it has no path of its own.
  var path: String {
    return self == .dashboard ? "" : rawValue
  }
}
`;

const ROUTE = `// Generated by plugins/withSiriShortcuts.js — edits here are discarded by prebuild.
import Foundation
import UIKit

/// Hands a dictated phrase to the app through its own URL scheme.
///
/// Going back out through the scheme, rather than reaching into storage from
/// Swift, is what keeps a Siri-created task identical to a typed one: the same
/// screen, the same validation, the same encrypted write, the same audit entry.
@available(iOS 16.0, *)
enum PlannerShortcutRoute {
  struct Draft {
    var title: String?
    var due: Date?
    var priority: PlannerPriority?
    var category: PlannerCategory?
    var notes: String?
  }

  /// Dates cross as yyyy-MM-dd and HH:mm in the device's own timezone, which is
  /// the shape the planner already stores. An ISO instant would be read back as
  /// UTC and land on the previous evening for anyone west of Greenwich.
  private static func dayFormatter() -> DateFormatter {
    let formatter = DateFormatter()
    formatter.locale = Locale(identifier: "en_US_POSIX")
    formatter.calendar = Calendar.current
    formatter.timeZone = TimeZone.current
    formatter.dateFormat = "yyyy-MM-dd"
    return formatter
  }

  private static func timeFormatter() -> DateFormatter {
    let formatter = dayFormatter()
    formatter.dateFormat = "HH:mm"
    return formatter
  }

  static func open(_ screen: String, draft: Draft?) {
    // Built through URLComponents so a dictated phrase containing "&" or "?" is
    // escaped rather than silently truncating everything after it.
    guard var components = URLComponents(string: "nwplanner://" + screen) else { return }

    var items: [URLQueryItem] = []
    if let draft = draft {
      let trimmed = (draft.title ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
      // Present but empty still means "open the form", ready to type into.
      items.append(URLQueryItem(name: "new", value: trimmed))

      if let due = draft.due {
        items.append(URLQueryItem(name: "due", value: dayFormatter().string(from: due)))
        // Siri gives midnight when only a day was said, and a task due "at
        // 00:00" would then alert at midnight, which nobody meant.
        let parts = Calendar.current.dateComponents([.hour, .minute], from: due)
        if (parts.hour ?? 0) != 0 || (parts.minute ?? 0) != 0 {
          items.append(URLQueryItem(name: "at", value: timeFormatter().string(from: due)))
        }
      }
      if let priority = draft.priority {
        items.append(URLQueryItem(name: "priority", value: priority.rawValue))
      }
      if let category = draft.category {
        items.append(URLQueryItem(name: "category", value: category.storedName))
      }
      if let notes = draft.notes, !notes.isEmpty {
        items.append(URLQueryItem(name: "notes", value: notes))
      }
    }
    if !items.isEmpty { components.queryItems = items }

    guard let url = components.url else { return }
    UIApplication.shared.open(url)
  }
}
`;

const INTENTS = `// Generated by plugins/withSiriShortcuts.js — edits here are discarded by prebuild.
import AppIntents
import Foundation

@available(iOS 16.0, *)
struct AddPlannerTaskIntent: AppIntent {
  static var title: LocalizedStringResource = "Add a task"
  static var description = IntentDescription(
    "Start a new task in NW Planner, with an optional due date, priority and category.",
    categoryName: "Tasks",
    searchKeywords: ["task", "homework", "assignment", "due", "todo"]
  )

  @Parameter(title: "Task", requestValueDialog: "What's the task?")
  var taskTitle: String

  // Optional, so Siri never interrogates the student for a date they did not
  // mention. The Shortcuts editor still offers a date picker for it.
  @Parameter(title: "Due")
  var due: Date?

  @Parameter(title: "Priority")
  var priority: PlannerPriority?

  @Parameter(title: "Category")
  var category: PlannerCategory?

  @Parameter(title: "Notes")
  var notes: String?

  static var parameterSummary: some ParameterSummary {
    When(\\.$due, .hasAnyValue) {
      Summary("Add \\(\\.$taskTitle) to NW Planner, due \\(\\.$due)") {
        \\.$priority
        \\.$category
        \\.$notes
      }
    } otherwise: {
      Summary("Add \\(\\.$taskTitle) to NW Planner") {
        \\.$due
        \\.$priority
        \\.$category
        \\.$notes
      }
    }
  }

  @MainActor
  func perform() async throws -> some IntentResult {
    PlannerShortcutRoute.open("tasks", draft: PlannerShortcutRoute.Draft(
      title: taskTitle, due: due, priority: priority, category: category, notes: notes
    ))
    return .result()
  }
}

@available(iOS 16.0, *)
struct AddPlannerReminderIntent: AppIntent {
  static var title: LocalizedStringResource = "Add a reminder"
  static var description = IntentDescription(
    "Start a new reminder in NW Planner.",
    categoryName: "Reminders",
    searchKeywords: ["reminder", "remind", "alert"]
  )

  @Parameter(title: "Reminder", requestValueDialog: "What should I remind you about?")
  var reminderTitle: String

  @Parameter(title: "When")
  var when: Date?

  @Parameter(title: "Notes")
  var notes: String?

  static var parameterSummary: some ParameterSummary {
    When(\\.$when, .hasAnyValue) {
      Summary("Remind me to \\(\\.$reminderTitle) at \\(\\.$when)") {
        \\.$notes
      }
    } otherwise: {
      Summary("Add \\(\\.$reminderTitle) to NW Planner") {
        \\.$when
        \\.$notes
      }
    }
  }

  @MainActor
  func perform() async throws -> some IntentResult {
    PlannerShortcutRoute.open("reminders", draft: PlannerShortcutRoute.Draft(
      title: reminderTitle, due: when, priority: nil, category: nil, notes: notes
    ))
    return .result()
  }
}

@available(iOS 16.0, *)
struct ShowPlannerScreenIntent: AppIntent {
  static var title: LocalizedStringResource = "Open NW Planner"
  static var description = IntentDescription(
    "Open NW Planner on a chosen screen.",
    categoryName: "Navigation"
  )

  @Parameter(title: "Screen", default: PlannerScreen.dashboard)
  var screen: PlannerScreen

  static var parameterSummary: some ParameterSummary {
    Summary("Open NW Planner on \\(\\.$screen)")
  }

  @MainActor
  func perform() async throws -> some IntentResult {
    PlannerShortcutRoute.open(screen.path, draft: nil)
    return .result()
  }
}

/// Answers out loud without launching the app.
///
/// Everything it reads is already rendered on the home screen and Lock Screen
/// by the widgets, so this exposes nothing new — but Siri may be answering on a
/// HomePod or in a car full of people, so it speaks counts and clock times and
/// never a record's title, whatever the widget titles setting says.
///
/// Returning an Int is what lets a student build their own shortcut around it:
/// "if what's due today is more than three, text my study group".
@available(iOS 16.0, *)
struct PlannerWorkloadIntent: AppIntent {
  static var title: LocalizedStringResource = "What's due today"
  static var description = IntentDescription(
    "Says how much is due today, without opening NW Planner.",
    categoryName: "Tasks",
    // resultValueName would label the returned number in the Shortcuts editor,
    // but that initialiser is iOS 17 and this app still supports 16.4.
    searchKeywords: ["due", "today", "workload", "how much", "busy"]
  )

  func perform() async throws -> some IntentResult & ReturnsValue<Int> & ProvidesDialog {
    guard let snapshot = PlannerSharedStore.snapshot() else {
      return .result(value: 0, dialog: "I couldn't reach your planner. Open NW Planner once, then try again.")
    }
    if snapshot.empty || (snapshot.totalToday == 0 && snapshot.overdue == 0) {
      return .result(value: 0, dialog: "Nothing scheduled today.")
    }

    var sentence = snapshot.dueToday == 1
      ? "One thing due today"
      : "\\(snapshot.dueToday) due today"

    if snapshot.overdue > 0 {
      sentence += snapshot.overdue == 1 ? ", and one overdue" : ", and \\(snapshot.overdue) overdue"
    }
    if let next = snapshot.nextAt {
      let formatter = DateFormatter()
      formatter.timeStyle = .short
      formatter.dateStyle = .none
      sentence += ". Next at \\(formatter.string(from: next))"
    }
    if snapshot.doneToday > 0 {
      sentence += ". You've finished \\(snapshot.doneToday)"
    }

    return .result(value: snapshot.dueToday, dialog: IntentDialog(stringLiteral: sentence + "."))
  }
}

// openAppWhenRun is deprecated in iOS 26 in favour of supportedModes, which
// does not exist on the iOS 16.4 floor this app supports. It still works, and
// .foreground(.immediate) would behave identically — so rather than branch for
// no user-visible difference, these use Apple's own documented backward
// compatible form, whose attribute also silences the SDK's warning.
@available(iOS 16.0, *)
@available(*, deprecated)
extension AddPlannerTaskIntent {
  static var openAppWhenRun: Bool { true }
}

@available(iOS 16.0, *)
@available(*, deprecated)
extension AddPlannerReminderIntent {
  static var openAppWhenRun: Bool { true }
}

@available(iOS 16.0, *)
@available(*, deprecated)
extension ShowPlannerScreenIntent {
  static var openAppWhenRun: Bool { true }
}
`;

const SHORTCUTS = `// Generated by plugins/withSiriShortcuts.js — edits here are discarded by prebuild.
import AppIntents

/// The four phrases Siri learns on install.
///
/// Apple allows ten and recommends between two and five; four covers the things
/// worth saying out loud without diluting recognition. Every intent above is
/// also an action in the Shortcuts app whether or not it appears here, so a
/// student can build their own multi-step shortcuts from all of them.
@available(iOS 16.0, *)
struct PlannerAppShortcuts: AppShortcutsProvider {
  // Every phrase has to name the app, or the system will not register it.
  static var appShortcuts: [AppShortcut] {
    AppShortcut(
      intent: AddPlannerTaskIntent(),
      phrases: [
        "Add a task to \\(.applicationName)",
        "New task in \\(.applicationName)",
        "Add homework to \\(.applicationName)",
      ],
      shortTitle: "Add Task",
      systemImageName: "checkmark.circle"
    )
    AppShortcut(
      intent: AddPlannerReminderIntent(),
      phrases: [
        "Add a reminder to \\(.applicationName)",
        "Remind me with \\(.applicationName)",
      ],
      shortTitle: "Add Reminder",
      systemImageName: "bell"
    )
    AppShortcut(
      intent: PlannerWorkloadIntent(),
      phrases: [
        "What's due today in \\(.applicationName)",
        "How much do I have in \\(.applicationName)",
        "\\(.applicationName) workload",
      ],
      shortTitle: "What's Due",
      systemImageName: "tray.full"
    )
    AppShortcut(
      intent: ShowPlannerScreenIntent(),
      phrases: [
        "Show my day in \\(.applicationName)",
        "Open \\(.applicationName)",
      ],
      shortTitle: "My Day",
      systemImageName: "calendar"
    )
  }
}
`;

const FILES = [
  ['PlannerSharedStore.swift', SHARED_STORE],
  ['PlannerEnums.swift', ENUMS],
  ['PlannerRoute.swift', ROUTE],
  ['PlannerIntents.swift', INTENTS],
  ['PlannerAppShortcuts.swift', SHORTCUTS],
];

module.exports = config =>
  FILES.reduce(
    (accumulated, [filePath, contents]) =>
      withBuildSourceFile(accumulated, { filePath, contents, overwrite: true }),
    config,
  );
