const { IOSConfig } = require('@expo/config-plugins');

const { withBuildSourceFile } = IOSConfig.XcodeProjectFile;

// Siri and the Shortcuts app, via App Intents.
//
// There is no Expo package for App Intents, so this is Swift the project owns.
// It is injected rather than committed under ios/, because ios/ is generated
// and gitignored — the same reason plugins/withUISceneLifecycle.js exists.
//
// Deliberately small. The intents do not create anything themselves: they open
// the app on the right screen with the dictated text as a query parameter, and
// the existing JavaScript does the work. That keeps every record inside the
// path it already travels — encrypted at rest, written through the audit log,
// queued in the outbox when offline — instead of growing a second, native way
// to create data that would have to reimplement all of it. It also means no
// entitlement, no extension target and no credential change: App Shortcuts are
// discovered from a type compiled into the app itself.
//
// Not done, on purpose: answering "what's due today" aloud. That needs the
// records readable outside the app, and Siri may speak them on a HomePod or in
// CarPlay, which is a much larger exposure than a widget for less value.

const SOURCE = `// Generated by plugins/withSiriShortcuts.js — edits here are discarded by prebuild.
import AppIntents
import UIKit

/// Hands a dictated phrase to the app through its own URL scheme.
///
/// Going back out through the scheme, rather than reaching into storage from
/// Swift, is what keeps a Siri-created task identical to a typed one: the same
/// screen, the same validation, the same encrypted write.
@available(iOS 16.0, *)
enum PlannerShortcutRoute {
  static func open(_ screen: String, draft: String?) {
    // Built through URLComponents so a dictated phrase containing "&" or "?"
    // is escaped rather than silently truncating the parameter.
    guard var components = URLComponents(string: "nwplanner://" + screen) else { return }
    if let draft, !draft.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
      components.queryItems = [URLQueryItem(name: "new", value: draft)]
    }
    guard let url = components.url else { return }
    UIApplication.shared.open(url)
  }
}

@available(iOS 16.0, *)
struct AddPlannerTaskIntent: AppIntent {
  static var title: LocalizedStringResource = "Add a task"
  static var description = IntentDescription("Start a new task in NW Planner.")

  // Deprecated in iOS 26 in favour of \`supportedModes\`, which does not exist on
  // the iOS 16 deployment target this app still supports. It continues to work,
  // and the replacement can be adopted when the floor moves.
  static var openAppWhenRun: Bool = true

  @Parameter(title: "Task", requestValueDialog: "What's the task?")
  var taskTitle: String

  @MainActor
  func perform() async throws -> some IntentResult {
    PlannerShortcutRoute.open("tasks", draft: taskTitle)
    return .result()
  }
}

@available(iOS 16.0, *)
struct AddPlannerReminderIntent: AppIntent {
  static var title: LocalizedStringResource = "Add a reminder"
  static var description = IntentDescription("Start a new reminder in NW Planner.")
  static var openAppWhenRun: Bool = true

  @Parameter(title: "Reminder", requestValueDialog: "What should I remind you about?")
  var reminderTitle: String

  @MainActor
  func perform() async throws -> some IntentResult {
    PlannerShortcutRoute.open("reminders", draft: reminderTitle)
    return .result()
  }
}

@available(iOS 16.0, *)
struct ShowPlannerDayIntent: AppIntent {
  static var title: LocalizedStringResource = "Show my day"
  static var description = IntentDescription("Open NW Planner on today's work.")
  static var openAppWhenRun: Bool = true

  @MainActor
  func perform() async throws -> some IntentResult {
    PlannerShortcutRoute.open("", draft: nil)
    return .result()
  }
}

@available(iOS 16.0, *)
struct PlannerAppShortcuts: AppShortcutsProvider {
  // Every phrase has to name the app, or the system will not register it.
  static var appShortcuts: [AppShortcut] {
    AppShortcut(
      intent: AddPlannerTaskIntent(),
      phrases: [
        "Add a task to \\(.applicationName)",
        "New task in \\(.applicationName)",
        "Add homework to \\(.applicationName)",
      ],
      shortTitle: "Add Task",
      systemImageName: "checkmark.circle"
    )
    AppShortcut(
      intent: AddPlannerReminderIntent(),
      phrases: [
        "Add a reminder to \\(.applicationName)",
        "Remind me with \\(.applicationName)",
      ],
      shortTitle: "Add Reminder",
      systemImageName: "bell"
    )
    AppShortcut(
      intent: ShowPlannerDayIntent(),
      phrases: [
        "Show my day in \\(.applicationName)",
        "Open \\(.applicationName)",
      ],
      shortTitle: "Show My Day",
      systemImageName: "calendar"
    )
  }
}
`;

module.exports = config =>
  withBuildSourceFile(config, {
    filePath: 'PlannerShortcuts.swift',
    contents: SOURCE,
    overwrite: true,
  });
